- name: configure payment component
  hosts: payment
  become: yes
  tasks:
  - name: install python 3
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - python3
    - gcc
    - python3-devel

  - name: Create a directory for roboshop user
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Add application User
    ansible.builtin.user:
      name: roboshop
      system: true
      home: /app
      # create_home: no
      shell: /sbin/nologin

  - name: Download the application code to created app directory.
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip
      dest: /tmp/payment.zip

  - name: unzip the downloaded files into user app directory
    ansible.builtin.unarchive:
      src: /tmp/payment.zip
      dest: /app
      remote_src: yes

  - name: download dependencies
    ansible.builtin.pip:
      requirements: requirements.txt
    args:
      chdir: /app
#-----------------------------------------------------
  - name: Setup SystemD Payment Service
    ansible.builtin.copy:
      src: payment.service
      dest: /etc/systemd/system/payment.service

  - name: Daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true
      name: payment

  - name: start and enable payment service
    ansible.builtin.service:
      name: payment
      state: restarted
      enabled: yes



