- name: configure shipping component
  hosts: shipping
  become: yes
  tasks:
  - name: install maven 
    ansible.builtin.package:
      name: maven
      state: present

  - name: Create a directory for roboshop user
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Add application User
    ansible.builtin.user:
      name: roboshop
      system: true
      home: /app
      # create_home: no
      shell: /sbin/nologin

  - name: Download the application code to created app directory.
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
      dest: /tmp/shipping.zip

  - name: unzip the downloaded files into user app directory
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes

  - name: download the dependencies
    ansible.builtin.command: mvn clean package 
    args:
      chdir: /app

  - name: rename the target jar folder
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar 
    args:
      chdir: /app

  - name: copy the shipping service file
    ansible.builtin.copy:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service

  - name: daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: start and enable shipping service
    ansible.builtin.service:
      name: shipping
      state: restarted
      enabled: yes

  - name: install mysql client
    ansible.builtin.package:
      name: mysql
      state: present
